services:
  product-mysql:
    image: mysql:8.0
    container_name: product-db
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=product
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=product
      - MYSQL_PASSWORD=product

  product-redis:
    image: redis:7.2.7
    container_name: product-redis
    ports:
      - "6379:6379"
